//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapis.Script.Execution {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lapis.Script.Execution.ExceptionResource", typeof(ExceptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is a constant that cannot be assigned a value. 的本地化字符串。
        /// </summary>
        internal static string _CannotAssignConst {
            get {
                return ResourceManager.GetString("_CannotAssignConst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The functions or methods cannot have a return value. 的本地化字符串。
        /// </summary>
        internal static string _CannotReturnWithValue {
            get {
                return ResourceManager.GetString("_CannotReturnWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected a return value. 的本地化字符串。
        /// </summary>
        internal static string _MustReturnWithValue {
            get {
                return ResourceManager.GetString("_MustReturnWithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unterminated string. 的本地化字符串。
        /// </summary>
        internal static string _UnterminatedString {
            get {
                return ResourceManager.GetString("_UnterminatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected statements of the property accessor or indexer. 的本地化字符串。
        /// </summary>
        internal static string AccessorStatementsExpected {
            get {
                return ResourceManager.GetString("AccessorStatementsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patterns of the l-value and r-value don&apos;t match. 的本地化字符串。
        /// </summary>
        internal static string ArrayAssignNotMatch {
            get {
                return ResourceManager.GetString("ArrayAssignNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Array index must be a non-negative integer. 的本地化字符串。
        /// </summary>
        internal static string ArrayIndexMustBePosInteger {
            get {
                return ResourceManager.GetString("ArrayIndexMustBePosInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of array must be a non-negative integer. 的本地化字符串。
        /// </summary>
        internal static string ArrayLengthMustBePosInteger {
            get {
                return ResourceManager.GetString("ArrayLengthMustBePosInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} conflicts with the automatically-generated parameters. 的本地化字符串。
        /// </summary>
        internal static string AutoParameterNameExist {
            get {
                return ResourceManager.GetString("AutoParameterNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto-implemented properties must define the get and set accessors. 的本地化字符串。
        /// </summary>
        internal static string AutoPropertyMustHasGetSet {
            get {
                return ResourceManager.GetString("AutoPropertyMustHasGetSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No enclosing loop out of which to break. 的本地化字符串。
        /// </summary>
        internal static string BreakMustBeInLoopOrSwitch {
            get {
                return ResourceManager.GetString("BreakMustBeInLoopOrSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is a type that cannot be assigned. 的本地化字符串。
        /// </summary>
        internal static string CannotAssignClass {
            get {
                return ResourceManager.GetString("CannotAssignClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is a function that cannot be assigned a value. 的本地化字符串。
        /// </summary>
        internal static string CannotAssignFunction {
            get {
                return ResourceManager.GetString("CannotAssignFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is a method that cannot be assigned a value. 的本地化字符串。
        /// </summary>
        internal static string CannotAssignMethod {
            get {
                return ResourceManager.GetString("CannotAssignMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static modifier here is invalid. 的本地化字符串。
        /// </summary>
        internal static string CannotBeStatic {
            get {
                return ResourceManager.GetString("CannotBeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The object cannot be converted to Boolean. 的本地化字符串。
        /// </summary>
        internal static string CannotConvertToBoolean {
            get {
                return ResourceManager.GetString("CannotConvertToBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The modifier is permitted on one only of the two accessors. 的本地化字符串。
        /// </summary>
        internal static string CannotUseBothGetSetModifier {
            get {
                return ResourceManager.GetString("CannotUseBothGetSetModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accessor modifiers can be used only if the property or indexer has both set and get accessors. 的本地化字符串。
        /// </summary>
        internal static string CannotUseGetSetModifier {
            get {
                return ResourceManager.GetString("CannotUseGetSetModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identifier {0} has been declared as type. 的本地化字符串。
        /// </summary>
        internal static string ClassAlreadyExists {
            get {
                return ResourceManager.GetString("ClassAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New operator must be applied to type. 的本地化字符串。
        /// </summary>
        internal static string ClassExpectedForNewExpression {
            get {
                return ResourceManager.GetString("ClassExpectedForNewExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructors must be public. 的本地化字符串。
        /// </summary>
        internal static string ConstructorMustBePublic {
            get {
                return ResourceManager.GetString("ConstructorMustBePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructor {0} does not accept the parameters. 的本地化字符串。
        /// </summary>
        internal static string ConstructorParemetersNotMatch {
            get {
                return ResourceManager.GetString("ConstructorParemetersNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No enclosing loop out of which to continue. 的本地化字符串。
        /// </summary>
        internal static string ContinueMustBeInLoop {
            get {
                return ResourceManager.GetString("ContinueMustBeInLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected {0}. 的本地化字符串。
        /// </summary>
        internal static string Expected {
            get {
                return ResourceManager.GetString("Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected an expression. 的本地化字符串。
        /// </summary>
        internal static string ExpressionExpected {
            get {
                return ResourceManager.GetString("ExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identifier {0} has been declared as function. 的本地化字符串。
        /// </summary>
        internal static string FunctionAlreadyExists {
            get {
                return ResourceManager.GetString("FunctionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only functions or methods can be invoked. 的本地化字符串。
        /// </summary>
        internal static string FunctionExpectedToInvoke {
            get {
                return ResourceManager.GetString("FunctionExpectedToInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The accessibility level on the accessor must be more restrictive than the accessibility level on the property or indexer itself. 的本地化字符串。
        /// </summary>
        internal static string GetSetModifierMoreStrictThanProperty {
            get {
                return ResourceManager.GetString("GetSetModifierMoreStrictThanProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected an identifier. 的本地化字符串。
        /// </summary>
        internal static string IdentifierExpected {
            get {
                return ResourceManager.GetString("IdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indexer already exists. 的本地化字符串。
        /// </summary>
        internal static string IndexerAlreadyExists {
            get {
                return ResourceManager.GetString("IndexerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The indexer cannot be assigned a value, because it is read-only. 的本地化字符串。
        /// </summary>
        internal static string IndexerIsReadonly {
            get {
                return ResourceManager.GetString("IndexerIsReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The indexer is write-only. 的本地化字符串。
        /// </summary>
        internal static string IndexerIsWriteonly {
            get {
                return ResourceManager.GetString("IndexerIsWriteonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The object does not support an indexer. 的本地化字符串。
        /// </summary>
        internal static string IndexerNotSupported {
            get {
                return ResourceManager.GetString("IndexerNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid expression. 的本地化字符串。
        /// </summary>
        internal static string InvalidExpression {
            get {
                return ResourceManager.GetString("InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid identifier. 的本地化字符串。
        /// </summary>
        internal static string InvalidIdentifier {
            get {
                return ResourceManager.GetString("InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid operator. 的本地化字符串。
        /// </summary>
        internal static string InvalidOperator {
            get {
                return ResourceManager.GetString("InvalidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid statement. 的本地化字符串。
        /// </summary>
        internal static string InvalidStatememt {
            get {
                return ResourceManager.GetString("InvalidStatememt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Super reference can only be used to access members of the super class, or call the constructor of super class. 的本地化字符串。
        /// </summary>
        internal static string InvalidSuper {
            get {
                return ResourceManager.GetString("InvalidSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label {0} already exists. 的本地化字符串。
        /// </summary>
        internal static string LabelAlreadyExists {
            get {
                return ResourceManager.GetString("LabelAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find label {0} within the scope of goto statement。 的本地化字符串。
        /// </summary>
        internal static string LabelNotFound {
            get {
                return ResourceManager.GetString("LabelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L-value can only be a variable, property or indexer. 的本地化字符串。
        /// </summary>
        internal static string LeftExpressionExpected {
            get {
                return ResourceManager.GetString("LeftExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member {0} already exists. 的本地化字符串。
        /// </summary>
        internal static string MemberAlreadyExists {
            get {
                return ResourceManager.GetString("MemberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected a property or method. 的本地化字符串。
        /// </summary>
        internal static string MemberExpected {
            get {
                return ResourceManager.GetString("MemberExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The object does not have a member named {0}. 的本地化字符串。
        /// </summary>
        internal static string MemberNotFound {
            get {
                return ResourceManager.GetString("MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple constructors are not allowed. 的本地化字符串。
        /// </summary>
        internal static string MultipleConstructors {
            get {
                return ResourceManager.GetString("MultipleConstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified class cannot be inherited. 的本地化字符串。
        /// </summary>
        internal static string NotInheritable {
            get {
                return ResourceManager.GetString("NotInheritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object reference not set to an instance of an object. 的本地化字符串。
        /// </summary>
        internal static string NullReference {
            get {
                return ResourceManager.GetString("NullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator {0} cannot be applied to the operands. 的本地化字符串。
        /// </summary>
        internal static string OperatorNotSupported {
            get {
                return ResourceManager.GetString("OperatorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional parameters must appear after all required parameters. 的本地化字符串。
        /// </summary>
        internal static string OptionalParameterMustBeAtLast {
            get {
                return ResourceManager.GetString("OptionalParameterMustBeAtLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter {0} already exists. 的本地化字符串。
        /// </summary>
        internal static string ParameterAlreadyExists {
            get {
                return ResourceManager.GetString("ParameterAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected parameters of the function or method. 的本地化字符串。
        /// </summary>
        internal static string ParemetersExpected {
            get {
                return ResourceManager.GetString("ParemetersExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The function, method or indexer does not accept the parameters. 的本地化字符串。
        /// </summary>
        internal static string ParemetersNotMatch {
            get {
                return ResourceManager.GetString("ParemetersNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property {0} cannot be assigned a value, because it is read-only. 的本地化字符串。
        /// </summary>
        internal static string PropertyIsReadonly {
            get {
                return ResourceManager.GetString("PropertyIsReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property {0} is write-only. 的本地化字符串。
        /// </summary>
        internal static string PropertyIsWriteonly {
            get {
                return ResourceManager.GetString("PropertyIsWriteonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return statements must be in the body of the function. 的本地化字符串。
        /// </summary>
        internal static string ReturnMustBeInFunction {
            get {
                return ResourceManager.GetString("ReturnMustBeInFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected a statement. 的本地化字符串。
        /// </summary>
        internal static string StatementExpected {
            get {
                return ResourceManager.GetString("StatementExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected statements of the function or method. 的本地化字符串。
        /// </summary>
        internal static string StatementsExpected {
            get {
                return ResourceManager.GetString("StatementsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Super call must be the first statement in the constructor. 的本地化字符串。
        /// </summary>
        internal static string SuperInvoke {
            get {
                return ResourceManager.GetString("SuperInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Super reference can only appear in the instance methods of derived class. 的本地化字符串。
        /// </summary>
        internal static string SuperMustBeInExtendedClass {
            get {
                return ResourceManager.GetString("SuperMustBeInExtendedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This reference can only appear in the instance methods. 的本地化字符串。
        /// </summary>
        internal static string ThisMustBeInInstanceMethod {
            get {
                return ResourceManager.GetString("ThisMustBeInInstanceMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected a type reference. 的本地化字符串。
        /// </summary>
        internal static string TypeExpected {
            get {
                return ResourceManager.GetString("TypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is undefined. 的本地化字符串。
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized escape character. 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedEscapeCharacter {
            get {
                return ResourceManager.GetString("UnrecognizedEscapeCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identifier {0} has been declared as variable. 的本地化字符串。
        /// </summary>
        internal static string VariableAlreadyExists {
            get {
                return ResourceManager.GetString("VariableAlreadyExists", resourceCulture);
            }
        }
    }
}
